import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h1">Hello World</Typography>
        <Typography variant="subtitle1">This is a paragrahp</Typography>
      </main>
    </>
  );
}
